all: sub

sub:
	(cd helloWorld; $(MAKE) all)
	(cd Common; $(MAKE) all)
	(cd SchwarmRandom; $(MAKE) all)
	(cd BossFish; $(MAKE) all)
	(cd SchwarmMonitorConsole; $(MAKE) all)

clean:
	(cd helloWorld; $(MAKE) clean)
	(cd Common; $(MAKE) clean)
	(cd SchwarmRandom; $(MAKE) clean)
	(cd BossFish; $(MAKE) clean)
	(cd SchwarmMonitorConsole; $(MAKE) clean)

test:
	(cd helloWorld; $(MAKE) test)
